### PR TITLE
Added build workflow

### PR DESCRIPTION
**Pull request by InitialXKO**
Triggering Github Action when pushing version tags, building mame-ao.exe for release.

### CODE REVIEW

**Comment by sam-ludlow** [comment]
Hello @InitialXKO I was looking at this, just had a chance to play properly yet.

**Comment by InitialXKO** [comment]
Hello, just put the yml there and publish your release with a new tag starts with a  letter v then github will build mame-ao.exe for you.  For example tag:v1.98

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cewatkins** [comment]
WOAH NOW, I tried to get codespaces to do it manually & the sdk instead os
csproj thing was a thing..
So, YAML, but getting it to build windows now, that a little trickier.

|)/`. /\/\/-\|) a ()xy()zb()urne venture

**Comment by cewatkins** [comment]
Also your change to MameAO.cs, is what I did too, but that's when I had it building with visual studio, you have it building on github.

**Pull request closed without merging**
